### ISSUE TITLE
Results about Cityscapes

### ISSUE THREAD

**Issue by Luffy03** [LiheYoung/ST-PlusPlus#11]
Congrats on CVPR first, nice work!
The detailed results about the cityscapes are not reported in the preprint. I wonder that have you compared your results with other sota methods on the cityscapes dataset?

**Comment by LiheYoung** [comment]
Hi, thanks very much!

We mainly compare our method with [DCC](https://github.com/dvlab-research/Context-Aware-Consistency) from CVPR'21, since we find our supervised baseline results are closest to DCC, thus the comparison is fair. We also notice that some other methods, such as [CPS](https://github.com/charlesCXK/TorchSemiSeg), report higher performance on Cityscapes. However, its supervised baseline results are also much higher than ours.

We have highlighted some training techniques from these works in the implementation details of our paper, such as OHEM, larger cropping size, and auxiliary supervision, which may further boost our performance. Besides, we also observe the sliding window evaluation strategy adopted by CPS can also improve our reported results by around 1.5%.

**Comment by Luffy03** [comment]
> Hi, thanks very much!
> 
> We mainly compare our method with [DCC](https://github.com/dvlab-research/Context-Aware-Consistency) from CVPR'21, since we find our supervised baseline results are closest to DCC, thus the comparison is fair. We also notice that some other methods, such as [CPS](https://github.com/charlesCXK/TorchSemiSeg), report higher performance on Cityscapes. However, its supervised baseline results are also much higher than ours.
> 
> We have highlighted some training techniques from these works in the implementation details of our paper, such as OHEM, larger cropping size, and auxiliary supervision, which may further boost our performance. Besides, we also observe the sliding window evaluation strategy adopted by CPS can also improve our reported results by around 1.5%.

Are these results reported in the CVPR paper? I did not see it in the preprint.

**Comment by LiheYoung** [comment]
Please refer to Table.4 for Cityscapes comparisons with most SOTA methods. And we didn't incorporate extra training/evaluation tricks.
