### ISSUE TITLE
Forget to ignore class 255 in caculating mIoU?

### ISSUE THREAD

**Issue by pascal1129** [LiheYoung/ST-PlusPlus#2]
https://github.com/LiheYoung/ST-PlusPlus/blob/4b0f5ba0859dd7b57c6117f6b99881cd36183387/utils.py#L16

Forget to ignore class 255 in caculating mIoU?

**Comment by Haochen-Wang409** [comment]
I'm also confused here. It seems like label 255 in GT will be replaced to background (label 0) for further evaluation.

**Comment by LiheYoung** [comment]
Hi, @pascal1129 and @Haochen-Wang409 

The class 255 is ignored in calculating the mIOU. 

The ``mask`` defined here indicates the valid regions that do not contain the 255 value, since the ``self.num_classes`` is only 21 for Pascal VOC dataset. In the following confusion matrix computation, both groundtruth mask (``label_true``) and predicted mask (``label_pred``) are filtered with the valid regions (``mask``).
https://github.com/LiheYoung/ST-PlusPlus/blob/7c31abfcf21e390a06c4d5da1f77a9fe5ff071ed/utils.py#L18-L19
