### ISSUE TITLE
Why "Re-initialize S" in Algorithm2?

### ISSUE THREAD

**Issue by yd-yin** [LiheYoung/ST-PlusPlus#25]
Hi! Thanks a lot for your great work!

In Algo2, after computing score $s_i$, ranking by the scores to get $D^{u_1}$ and $D^{u_2}$, there is a line saying "Re-initialize S".

Does it mean to re-initialize the weight of the student model to the initialized random parameters? Why the re-initialization is needed? I think I did not find the relevant words in the text.

Thanks!

**Comment by LiheYoung** [comment]
Hi,

In practice, we find that re-initializing the model helps achieve better results. The model pre-trained on $D^l$ and $D^{u_1}$ will suffer from some confirmation bias due to the incorrect labels in $D^{u1}$. Intuitively, a re-initialization will eliminate the negative effect. Most related works in the field of self-training also adopt such a practice.

**Comment by yd-yin** [comment]
I got it. Thanks for your really quick response!
