### ISSUE TITLE
Question about the "Comparison with state-of-the-art methods" section

### ISSUE THREAD

**Issue by chaochao42** [LiheYoung/ST-PlusPlus#4]
Hello, thank for your insightful and ingenious work. After thorough reading, I have a simple question that why CPS(Semi-Supervised Semantic Segmentation with Cross Pseudo Supervision) is not compared with ST++, since CPS is a previous SOTA  work?

**Comment by LiheYoung** [comment]
Hi, thanks for your question.

Our work is concurrent with CPS. By the time of our submission, CPS has not yet been available publicly. CPS is available on arXiv on June 2, while ours is submitted on May 28 and available on arXiv on June 9.

Actually, our ST++ performance is slightly better than CPS on Pascal VOC across most settings, especially when considering CPS adopts a ResNet with the deep stem block, which is stronger than our classical ResNet. As for Cityscapes, since CPS introduces extra training strategies, such as OHEM and SyncBN, it is hard to be directly compared.

We may add the comparisons in our future version.

**Comment by chaochao42** [comment]
Ok, thank you for your answer.
